name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install correct version of Node
        shell: bash -l {0}
        run: nvm install

      - name: Install correct version of Yarn
        run: yarn policies set-version $(cat .yvmrc)

      - name: Install build dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn run lint

      - name: Run tests
        run: yarn run test
