name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install release dependencies
        run: yarn install --frozen-lockfile

      - name: Build and publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LEDERER_TOKEN }}
