name: Release

on:
  push:
    branches:
      - feature/cek/release-workflow
    tags:
      - "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Install release dependencies
        run: yarn install --frozen-lockfile

      - name: Build and publish package
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AZAVEA_TOKEN }}
